version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine #rabbitmq:3.8-management-alpine
    container_name: cmt-rabbitmq
    hostname: cmt-rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
