export enum EnvEnum {
  PORT = 'PORT',

  RABBITMQ_DEFAULT_USER = 'RABBITMQ_DEFAULT_USER',
  RABBITMQ_DEFAULT_PASS = 'RABBITMQ_DEFAULT_PASS',
  RABBITMQ_USER = 'RABBITMQ_USER',
  RABBITMQ_PASS = 'RABBITMQ_PASS',
  RABBITMQ_HOST = 'RABBITMQ_HOST',

  RABBITMQ_AUTH_QUEUE = 'RABBITMQ_AUTH_QUEUE',

  COOKIE_HTTP_ONLY = 'COOKIE_HTTP_ONLY',
  COOKIE_SECURE = 'COOKIE_SECURE',

  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  EXPIRESIN_ACCESS_TOKEN = 'EXPIRESIN_ACCESS_TOKEN',
  EXPIRESIN_REFRESH_TOKEN = 'EXPIRESIN_REFRESH_TOKEN',
}
